var money = 1000;
var income = "Some text";
var addExpenses = 'Text, More_text, Text';
var deposit = true;
var mission = 100000;
var period = 6;
var budgetDay = 30;
var num = 266219;
num = String(num).split("").reduce((last, next) => last * next)**3;
console.log(String(num).substr(0,2));

alert("Some text");
console.log("Some text");
console.log("Type of money: " + typeof(money));
console.log("Type of income: " + typeof(income));
console.log("Type of deposit: " + typeof(deposit));
console.log("Length of addExpenses: " + addExpenses.length);
console.log(addExpenses.toLowerCase().split(', '));
console.log("Период равен " + period + " месяцев");
console.log("Цель заработать " + mission + " рублей");
console.log("budgetDay: " + 30);